### ISSUE TITLE
Modifying components package and see updates in app without rebuild?

### ISSUE THREAD

**Issue by cmdcolin** [cadbox1/react-monorepo-2020#1]
If I clone the repo, modify the Button component to just say "Push me" in Button.tsx, and then run app, it does not say "Push me"

How would you suggest getting that sort of live update?

**Comment by cadbox1** [comment]
Hi Colin!

You can run the ‘yarn build-watch’ in the components package to
continuously build the components package and have the changes show up in
the app.

Otherwise you can run ‘yarn build’ for once off builds after developing
your component in storybook.

https://github.com/cadbox1/react-monorepo-2020/tree/master/packages/components#-running-locally

Let me know how you go!

**Comment by cmdcolin** [comment]
Thanks :) saw that in the repo now.  I have another monorepo project I work on where it will automatically watch other packages for changes when you are running `yarn start` in the CRA subpackage but honestly the configuration for it is crazy so it's good to see this example...

**Comment by cadbox1** [comment]
Awesome! Give it a star if you like.

Yeah, this workspace stuff is still ongoing I think. Not sure if you’re
using it but Gatsby behaves differently to CRA and wants to compile the
packages in your workspace while CRA doesn’t. Quick workaround for me was
to turn off eslint in Gatsby so it stopped linting my already compiled
package.

https://github.com/cadbox1/very-nested/tree/master/packages/website
